spring:
  application:
    name: auth-service

  mongodb:
    uri: mongodb://localhost:27017/instagram_auth

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics

jwt:
  secret: "Your-secretkey"
  expiration: 3600000