server:
  port: 8084

spring:
  application:
    name: notification-service

  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/instagram_notifications}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.masu.events
        spring.json.use.type.headers: true
    listener:
      missing-topics-fatal: false

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info
