server:
  port: 8080

spring:
  application:
    name: api-gateway

  codec:
    max-in-memory-size: 16MB

  cloud:
    gateway:
      server:
        webflux:
          routes:

            # Auth Service
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/auth/**

            # Posts for a user (must be before user-service)
            - id: user-posts
              uri: ${POST_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/api/v1/users/*/posts

            # User Service
            - id: user-service
              uri: ${USER_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/v1/users/**

            # Post Service
            - id: post-service
              uri: ${POST_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/api/v1/posts/**

            - id: comment-service
              uri: ${POST_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/api/v1/comments/**

            # Notification Service
            - id: notification-service
              uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8084}
              predicates:
                - Path=/api/v1/notifications/**

management:
  endpoint:
    gateway:
      access: read-only

  endpoints:
    web:
      exposure:
        include: health,info,gateway

