server:
  port: 8083

spring:
  application:
    name: post-service

  codec:
    max-in-memory-size: 16MB

  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/instagram_posts}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: post-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.masu.events

jwt:
  secret: ${JWT_SECRET}

user-service:
  url: ${USER_SERVICE_URL:http://localhost:8082}

notification-service:
  url: ${NOTIFICATION_SERVICE_URL:http://localhost:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info